import { expect, test } from '@playwright/test'
import { formatDate, getI18n, localizedPath } from '../lib/i18n'
import { describeCalendarFileError, describeCalendarFileRead } from '../lib/calendar-files'

test('locale helpers preserve routes, values, and calendar messages', () => {
  expect(localizedPath('/?edit=abc#dates', 'en')).toBe('/en/?edit=abc#dates')
  expect(localizedPath('/en/e/abc', 'ja')).toBe('/e/abc')
  expect(localizedPath('/en', 'ja')).toBe('/')
  expect(localizedPath('/english', 'ja')).toBe('/english')
  expect(localizedPath('https://example.com', 'en')).toBe('https://example.com')
  expect(formatDate('2026-09-14', 'en')).toBe('Mon, Sep 14')
  expect(getI18n('en').t('{0} さんの回答を削除します。', '日本語 {1}')).toBe('Delete the response from 日本語 {1}?')
  expect(describeCalendarFileError(new Error('NO_ICS_IN_ZIP'), 'en')).toContain('No .ics files')
  expect(describeCalendarFileRead({ isZip: true, texts: [{ name: 'work.ics', text: '' }], skippedBirthdayNames: ['birthday.ics'], totalIcsCount: 2 }, 'en')).toBe('Processed 1 calendar files from the ZIP. Excluded 1 birthday calendars.')
})

test('English create, answer, edit, history, language switch, and mobile layout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/en')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en')
  await expect(page).toHaveTitle(/Nitteigumi/)
  await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', /\/en$/)
  await expect(page.locator('link[rel="manifest"]')).toHaveAttribute('href', '/en/manifest.webmanifest')
  const manifest = await page.request.get('/en/manifest.webmanifest')
  expect(manifest.ok()).toBe(true)
  expect(await manifest.json()).toMatchObject({ name: 'Nitteigumi', lang: 'en', start_url: 'https://nittei-app.qoj.workers.dev/en' })
  await page.getByPlaceholder('e.g. Dinner with friends').fill('English test 日本語')
  await page.getByPlaceholder('Location, details, and what each answer symbol means').fill('○: Available; △: Maybe; ✕: Busy')
  await page.getByRole('button', { name: '◎ / ○ / △ / ✕', exact: true }).click()
  await page.getByRole('button', { name: 'No time', exact: true }).click()
  await expect(page.locator('input[type="time"]').first()).toHaveValue('')
  await page.getByRole('button', { name: '📅 Add date range', exact: true }).click()
  const range = page.locator('.fixed.inset-0')
  await range.locator('input[type="date"]').nth(0).fill('2026-09-14')
  await range.locator('input[type="date"]').nth(1).fill('2026-09-16')
  await range.getByRole('button', { name: 'Add dates (3)', exact: true }).click()
  await expect(page.locator('input[type="date"]')).toHaveCount(3)
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await page.screenshot({ path: `test-results/english-home-${width}.png`, fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    const inputs = await page.locator('.candidate-row').first().evaluate(row => {
      const date = row.querySelector('input[type="date"]')!.getBoundingClientRect()
      const time = row.querySelector('input[type="time"]')!.getBoundingClientRect()
      const parent = row.getBoundingClientRect()
      return { dateRight: date.right, dateBottom: date.bottom, timeLeft: time.left, timeTop: time.top, parentRight: parent.right }
    })
    expect(inputs.dateRight).toBeLessThanOrEqual(inputs.parentRight)
    expect(inputs.dateBottom <= inputs.timeTop || inputs.dateRight <= inputs.timeLeft).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('button', { name: '↶ Undo', exact: true }).click()
  await expect(page.locator('input[type="date"]')).toHaveCount(0)
  await page.getByRole('button', { name: '↷ Redo', exact: true }).click()
  await expect(page.locator('input[type="date"]')).toHaveCount(3)
  await page.getByRole('button', { name: 'Create event', exact: true }).first().click()
  await page.waitForURL(/\/en\/e\/[a-z0-9]+$/)
  const englishUrl = page.url()
  await expect(page.getByRole('heading', { level: 1, name: 'English test 日本語' })).toBeVisible()
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/)
  await page.getByPlaceholder('e.g. Alex').fill('Alex')
  const firstAnswer = page.locator('[data-answer-candidate-id][data-answer-value="○"]').first()
  await firstAnswer.click()
  await expect(firstAnswer).toHaveClass(/bg-emerald-50/)
  await page.getByRole('button', { name: '↶ Undo', exact: true }).click()
  await expect(firstAnswer).not.toHaveClass(/bg-emerald-50/)
  await page.getByRole('button', { name: '↷ Redo', exact: true }).click()
  await expect(firstAnswer).toHaveClass(/bg-emerald-50/)
  await page.getByRole('button', { name: 'Submit response', exact: true }).click()
  await expect(page.locator('table')).toContainText('Alex')
  await page.getByRole('button', { name: 'Edit', exact: true }).first().click()
  await expect(page.getByPlaceholder('e.g. Alex')).toHaveValue('Alex')
  await page.getByPlaceholder('e.g. Alex').fill('A')
  await page.getByRole('button', { name: 'Update response', exact: true }).click()
  await expect(page.locator('table')).toContainText('A')
  await page.getByRole('link', { name: 'Edit event', exact: true }).click()
  await expect(page.getByPlaceholder('e.g. Dinner with friends')).toHaveValue('English test 日本語')
  await page.getByRole('button', { name: 'Save changes', exact: true }).first().click()
  await page.waitForURL(englishUrl)

  await page.getByRole('button', { name: 'Settings', exact: false }).click()
  await expect(page.getByText('Busy:', { exact: true })).toBeVisible()
  await page.locator('input[type="file"]').setInputFiles({
    name: 'calendar.ics', mimeType: 'text/calendar',
    buffer: Buffer.from('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:english-test\r\nDTSTAMP:20260901T000000Z\r\nDTSTART;VALUE=DATE:20260914\r\nDTEND;VALUE=DATE:20260915\r\nSUMMARY:Busy\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n'),
  })
  await expect(page.getByText('Calendar file processed. Please review your answers before submitting.')).toBeVisible()
  await expect(page.locator('[data-answer-candidate-id][data-answer-value="✕"]').first()).toHaveClass(/bg-stone-100/)
  await page.getByRole('button', { name: '↶ Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Settings', exact: false }).click()

  await page.getByRole('link', { name: '日本語', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
  await expect(page.getByRole('heading', { name: 'みんなの回答', exact: true })).toBeVisible()
  await expect(page.locator('table')).toContainText('A')
  await page.getByRole('link', { name: 'English', exact: true }).click()
  await page.waitForURL(englishUrl)

  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await page.locator('[data-answer-candidate-id][data-answer-value="-"]').first().click()
    await page.getByPlaceholder('Note (optional)', { exact: true }).first().fill('Evening')
    await expect(page.getByRole('button', { name: 'Submit response', exact: true })).toBeVisible()
    const geometry = await page.evaluate(() => {
      const row = document.querySelector('[data-answer-row-id]')!
      const last = row.querySelector('input')!.getBoundingClientRect()
      return { scroll: document.documentElement.scrollWidth, viewport: innerWidth, lastRight: last.right }
    })
    expect(geometry.scroll).toBeLessThanOrEqual(width)
    expect(geometry.lastRight).toBeLessThanOrEqual(width)
    await page.screenshot({ path: `test-results/english-response-${width}.png`, fullPage: true })
    await page.getByRole('button', { name: '↶ Undo', exact: true }).click()
  }
  await page.getByRole('link', { name: 'Recent events', exact: true }).click()
  await expect(page.getByRole('link', { name: 'English test 日本語' })).toHaveAttribute('href', /\/en\/e\//)
  for (const [route, heading] of [['contact', 'Contact'], ['privacy', 'Privacy Policy'], ['terms', 'Terms of Use']]) {
    await page.goto(`/en/${route}`)
    await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
    expect(await page.locator('body').innerText()).not.toMatch(/[ぁ-んァ-ヶ]/)
  }
  expect(errors).toEqual([])
})

test('calendar drag reversal, selection undo, theme, and edit-link locale', async ({ page }) => {
  await page.goto('/en')
  const first = page.locator('[data-calendar-date]').nth(10)
  const last = page.locator('[data-calendar-date]').nth(12)
  await first.scrollIntoViewIfNeeded()
  const a = (await first.boundingBox())!
  const b = (await last.boundingBox())!
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2)
  await page.mouse.down()
  await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 8 })
  await expect(page.locator('[data-calendar-date].bg-rose-700')).toHaveCount(3)
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('[data-calendar-date].bg-rose-700')).toHaveCount(0)
  await page.getByRole('button', { name: /Select remaining days/ }).click()
  expect(await page.locator('[data-calendar-date].bg-rose-700').count()).toBeGreaterThan(0)
  await page.getByRole('button', { name: '↶ Undo', exact: true }).click()
  await expect(page.locator('[data-calendar-date].bg-rose-700')).toHaveCount(0)
  await page.getByRole('button', { name: '↷ Redo', exact: true }).click()
  expect(await page.locator('[data-calendar-date].bg-rose-700').count()).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Switch to dark mode', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/english-home-dark.png', fullPage: true })
  await page.goto('/en?edit=missing#dates')
  await page.getByRole('link', { name: '日本語', exact: true }).click()
  await expect(page).toHaveURL(/\/\?edit=missing#dates$/)
  await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})
